import { HardwareProfile } from './types';

export const HARDWARE_PROFILES: HardwareProfile[] = [
  // --- NVIDIA RTX DESKTOP GENERATIONS (GDDR7 & GDDR6X) ---
  {
    id: 'rtx-5090',
    name: 'NVIDIA RTX 5090 (Blackwell Flagship)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop (Next-Gen)',
    memoryType: '32GB GDDR7',
    vram: 32,
    memoryBandwidth: 1792,
    estimatedPriceUSD: 1999,
    powerConsumptionWatts: 600,
    tpsScaling: 0.98,
    description: 'The supreme peak of consumer local inference. Enormous 32GB of state-of-the-art GDDR7 memory allows running huge 32B models in FP16 or high quant configurations of massive 70B models completely in VRAM.'
  },
  {
    id: 'rtx-5080',
    name: 'NVIDIA RTX 5080',
    category: 'gpu',
    platformType: 'NVIDIA Desktop (Next-Gen)',
    memoryType: '16GB GDDR7',
    vram: 16,
    memoryBandwidth: 1008,
    estimatedPriceUSD: 999,
    powerConsumptionWatts: 400,
    tpsScaling: 0.96,
    description: 'Outstanding next-generation speed driven by blazing GDDR7 bandwidth. Captivating performance for 8B and 14B parameter context limits.'
  },
  {
    id: 'rtx-5070',
    name: 'NVIDIA RTX 5070',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '12GB GDDR7',
    vram: 12,
    memoryBandwidth: 672,
    estimatedPriceUSD: 649,
    powerConsumptionWatts: 250,
    tpsScaling: 0.94,
    description: 'High-velocity entry into next-generation Blackwell architecture. GDDR7 speeds stream medium/light models almost instantly.'
  },
  {
    id: 'rtx-4090',
    name: 'NVIDIA RTX 4090 (Single)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '24GB GDDR6X',
    vram: 24,
    memoryBandwidth: 1008,
    estimatedPriceUSD: 1699,
    powerConsumptionWatts: 450,
    tpsScaling: 0.95,
    description: 'The standard premium consumer benchmark. Incredible bandwidth and matrix cores deliver unmatched speed for models under 24GB.'
  },
  {
    id: 'rtx-4080-super',
    name: 'NVIDIA RTX 4080 Super',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '16GB GDDR6X',
    vram: 16,
    memoryBandwidth: 736,
    estimatedPriceUSD: 999,
    powerConsumptionWatts: 320,
    tpsScaling: 0.93,
    description: 'Highly responsive 16GB discrete GPU. Balanced Core counts provide lightning fast token stream speed for 8B to 14B parameter models.'
  },
  {
    id: 'rtx-4080',
    name: 'NVIDIA RTX 4080',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '16GB GDDR6X',
    vram: 16,
    memoryBandwidth: 717,
    estimatedPriceUSD: 1099,
    powerConsumptionWatts: 320,
    tpsScaling: 0.92,
    description: 'Original Ada Lovelace 16GB runner. Highly agile local accelerator across modern AI ecosystems.'
  },
  {
    id: 'rtx-4070-ti-super',
    name: 'NVIDIA RTX 4070 Ti Super',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '16GB GDDR6',
    vram: 16,
    memoryBandwidth: 672,
    estimatedPriceUSD: 799,
    powerConsumptionWatts: 285,
    tpsScaling: 0.92,
    description: 'The budget-conscious local AI community superstar. 16GB VRAM on a 256-bit bus makes it the cheapest gateway to zero-offload inference.'
  },
  {
    id: 'rtx-4070-ti',
    name: 'NVIDIA RTX 4070 Ti',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '12GB GDDR6X',
    vram: 12,
    memoryBandwidth: 504,
    estimatedPriceUSD: 749,
    powerConsumptionWatts: 285,
    tpsScaling: 0.91,
    description: 'Fast 12GB performance card. Handles 8B-11B parameter models inside high quantization boundaries without stutter.'
  },
  {
    id: 'rtx-4070-super',
    name: 'NVIDIA RTX 4070 Super',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '12GB GDDR6X',
    vram: 12,
    memoryBandwidth: 504,
    estimatedPriceUSD: 599,
    powerConsumptionWatts: 220,
    tpsScaling: 0.91,
    description: 'Superb balance of visual power and AI execution. Outstanding Tensor processing power for neural workloads.'
  },
  {
    id: 'rtx-4070',
    name: 'NVIDIA RTX 4070',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '12GB GDDR6X',
    vram: 12,
    memoryBandwidth: 504,
    estimatedPriceUSD: 549,
    powerConsumptionWatts: 200,
    tpsScaling: 0.90,
    description: 'An extremely efficient and quiet desktop card. Perfect entry point to explore 8B models fully offline.'
  },
  {
    id: 'rtx-4060-ti-16',
    name: 'NVIDIA RTX 4060 Ti (16GB)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '16GB GDDR6',
    vram: 16,
    memoryBandwidth: 288,
    estimatedPriceUSD: 449,
    powerConsumptionWatts: 160,
    tpsScaling: 0.85,
    description: 'Valued for its unique 16GB layout on a budget. A tighter 128-bit memory bus bottleneck dampens top speeds, but fits large files easily.'
  },
  {
    id: 'rtx-4060-ti-8',
    name: 'NVIDIA RTX 4060 Ti (8GB)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '8GB GDDR6',
    vram: 8,
    memoryBandwidth: 288,
    estimatedPriceUSD: 389,
    powerConsumptionWatts: 160,
    tpsScaling: 0.84,
    description: 'Compact mid-range card. Highly efficient engine for lightweight 1.5B, 3B, or heavily quantized 8B models.'
  },
  {
    id: 'rtx-4060',
    name: 'NVIDIA RTX 4060',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '8GB GDDR6',
    vram: 8,
    memoryBandwidth: 272,
    estimatedPriceUSD: 299,
    powerConsumptionWatts: 115,
    tpsScaling: 0.83,
    description: 'Extremely cool-running entry unit. Excellent for desktop sandboxing and developing basic edge interfaces.'
  },
  {
    id: 'rtx-3090-ti',
    name: 'NVIDIA RTX 3090 Ti',
    category: 'gpu',
    platformType: 'NVIDIA Desktop (Ampere)',
    memoryType: '24GB GDDR6X',
    vram: 24,
    memoryBandwidth: 1008,
    estimatedPriceUSD: 850,
    powerConsumptionWatts: 450,
    tpsScaling: 0.92,
    description: 'Maxed-out Ampere titan. Massive bandwidth matches RTX 4090 speeds, though energy pull is highly demanding.'
  },
  {
    id: 'rtx-3090',
    name: 'NVIDIA RTX 3090',
    category: 'gpu',
    platformType: 'NVIDIA Desktop (Ampere)',
    memoryType: '24GB GDDR6X',
    vram: 24,
    memoryBandwidth: 936,
    estimatedPriceUSD: 700,
    powerConsumptionWatts: 350,
    tpsScaling: 0.91,
    description: 'The ultimate secondary-market value king. Unlocks a full 24GB high-speed framebuffer for running 32B and 70B models at excellent prices.'
  },
  {
    id: 'rtx-3080-ti',
    name: 'NVIDIA RTX 3080 Ti',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '12GB GDDR6X',
    vram: 12,
    memoryBandwidth: 912,
    estimatedPriceUSD: 450,
    powerConsumptionWatts: 350,
    tpsScaling: 0.89,
    description: 'Generous 384-bit bus speeds up smaller LLMs immensely. Restrained slightly by its 12GB core buffer ceiling.'
  },
  {
    id: 'rtx-3080-12g',
    name: 'NVIDIA RTX 3080 (12GB)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '12GB GDDR6X',
    vram: 12,
    memoryBandwidth: 912,
    estimatedPriceUSD: 400,
    powerConsumptionWatts: 350,
    tpsScaling: 0.88,
    description: 'Solid high-bandwidth Ampere option. Blazing generation speeds, though memory caps limit large prefill queries.'
  },
  {
    id: 'rtx-3080-10g',
    name: 'NVIDIA RTX 3080 (10GB)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '10GB GDDR6X',
    vram: 10,
    memoryBandwidth: 760,
    estimatedPriceUSD: 350,
    powerConsumptionWatts: 320,
    tpsScaling: 0.87,
    description: 'Historic gaming favorite. Offers immense core speeds but fits restricted model weights.'
  },
  {
    id: 'rtx-3070-ti',
    name: 'NVIDIA RTX 3070 Ti',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '8GB GDDR6X',
    vram: 8,
    memoryBandwidth: 608,
    estimatedPriceUSD: 300,
    powerConsumptionWatts: 290,
    tpsScaling: 0.86,
    description: 'Fast GDDR6X bus yields impressive speeds for 1.5B and 3B parameter models, though VRAM is constrained.'
  },
  {
    id: 'rtx-3070',
    name: 'NVIDIA RTX 3070',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '8GB GDDR6',
    vram: 8,
    memoryBandwidth: 448,
    estimatedPriceUSD: 250,
    powerConsumptionWatts: 220,
    tpsScaling: 0.85,
    description: 'Highly common desktop accelerator. Outstanding budget baseline for lightweight local neural models.'
  },
  {
    id: 'rtx-3060-ti',
    name: 'NVIDIA RTX 3060 Ti',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '8GB GDDR6',
    vram: 8,
    memoryBandwidth: 448,
    estimatedPriceUSD: 230,
    powerConsumptionWatts: 200,
    tpsScaling: 0.84,
    description: 'Reliability driver. Great for developers working on tiny edge adapters and code-completion helpers.'
  },
  {
    id: 'rtx-3060-12b',
    name: 'NVIDIA RTX 3060 (12GB)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '12GB GDDR6',
    vram: 12,
    memoryBandwidth: 360,
    estimatedPriceUSD: 289,
    powerConsumptionWatts: 170,
    tpsScaling: 0.90,
    description: 'Ultimate budget entry platform. Generous 12GB of VRAM allows flawless execution of 8B models without any expensive system swap.'
  },
  {
    id: 'rtx-3050-8b',
    name: 'NVIDIA RTX 3050 (8GB)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop',
    memoryType: '8GB GDDR6',
    vram: 8,
    memoryBandwidth: 224,
    estimatedPriceUSD: 169,
    powerConsumptionWatts: 130,
    tpsScaling: 0.80,
    description: 'Minimalist starter hardware. Useful for playing with low context 3B scale systems.'
  },

  // --- MULTI-GPU DESKTOP CONFIGS ---
  {
    id: 'dual-rtx-4090',
    name: 'Dual NVIDIA RTX 4090 (Linked/Split)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop (Multi-GPU)',
    memoryType: '48GB GDDR6X (Combined)',
    vram: 48,
    memoryBandwidth: 1800,
    estimatedPriceUSD: 3398,
    powerConsumptionWatts: 900,
    tpsScaling: 0.88,
    description: 'Enthusiast workstation dream. Massive 48GB combined buffer runs full-scale 70B models at screaming token speeds.'
  },
  {
    id: 'dual-rtx-3090',
    name: 'Dual NVIDIA RTX 3090 (Split)',
    category: 'gpu',
    platformType: 'NVIDIA Desktop (Multi-GPU)',
    memoryType: '48GB GDDR6X (Combined)',
    vram: 48,
    memoryBandwidth: 1400,
    estimatedPriceUSD: 1400,
    powerConsumptionWatts: 700,
    tpsScaling: 0.85,
    description: 'The legendary consumer budget build for high-end local AI. 48GB VRAM runs 70B and 34B models with fast processing.'
  },

  // --- NVIDIA WORKSTATION & PROFESSIONAL ADA RANGE ---
  {
    id: 'rtx-spark-sff',
    name: 'NVIDIA RTX Spark (Low-Profile SFF Concept)',
    category: 'gpu',
    platformType: 'NVIDIA Workstation (Special)',
    memoryType: '24GB GDDR7',
    vram: 24,
    memoryBandwidth: 1008,
    estimatedPriceUSD: 1899,
    powerConsumptionWatts: 250,
    tpsScaling: 0.96,
    description: 'Compact high-density local AI powerhouse. Incorporates top-tier Blackwell mobility parameters in an ultra-low profile silent chassis designed for decentralized edge servers.'
  },
  {
    id: 'rtx-4000-sff-ada',
    name: 'NVIDIA RTX 4000 SFF Ada Generation',
    category: 'gpu',
    platformType: 'NVIDIA Workstation',
    memoryType: '20GB GDDR6 (ECC)',
    vram: 20,
    memoryBandwidth: 280,
    estimatedPriceUSD: 1250,
    powerConsumptionWatts: 70,
    tpsScaling: 0.88,
    description: 'Revolutionary low-power professional card. Pulls only 70W yet houses a massive 20GB of ECC video memory, fitting easily into compact business clients.'
  },
  {
    id: 'rtx-6000-ada',
    name: 'NVIDIA RTX 6000 Ada',
    category: 'gpu',
    platformType: 'NVIDIA Workstation (Professional)',
    memoryType: '48GB GDDR6 (ECC)',
    vram: 48,
    memoryBandwidth: 960,
    estimatedPriceUSD: 6800,
    powerConsumptionWatts: 300,
    tpsScaling: 0.96,
    description: 'Designed for silent, enterprise-grade calculation. Exceptional build quality with 48GB of ECC VRAM inside a compact 300W frame.'
  },
  {
    id: 'rtx-5880-ada',
    name: 'NVIDIA RTX 5880 Ada Generation',
    category: 'gpu',
    platformType: 'NVIDIA Workstation (Professional)',
    memoryType: '48GB GDDR6 (ECC)',
    vram: 48,
    memoryBandwidth: 960,
    estimatedPriceUSD: 5999,
    powerConsumptionWatts: 285,
    tpsScaling: 0.94,
    description: 'Sub-flagship runtime GPU specialized for professional design and localized neural rendering without intense thermal exhaust.'
  },
  {
    id: 'rtx-5000-ada',
    name: 'NVIDIA RTX 5000 Ada Generation',
    category: 'gpu',
    platformType: 'NVIDIA Workstation',
    memoryType: '32GB GDDR6 (ECC)',
    vram: 32,
    memoryBandwidth: 576,
    estimatedPriceUSD: 3999,
    powerConsumptionWatts: 250,
    tpsScaling: 0.93,
    description: 'Invaluable 32GB mid-block enterprise runner. Handles deep model quants with highly-stable processing reliability.'
  },
  {
    id: 'rtx-4500-ada',
    name: 'NVIDIA RTX 4500 Ada Generation',
    category: 'gpu',
    platformType: 'NVIDIA Workstation',
    memoryType: '24GB GDDR6 (ECC)',
    vram: 24,
    memoryBandwidth: 432,
    estimatedPriceUSD: 2250,
    powerConsumptionWatts: 210,
    tpsScaling: 0.92,
    description: 'Excellent balance of space and stability. Provides the iconic 24GB workspace buffer with low structural heat generation.'
  },
  {
    id: 'rtx-a6000',
    name: 'NVIDIA RTX A6000',
    category: 'gpu',
    platformType: 'NVIDIA Workstation',
    memoryType: '48GB GDDR6',
    vram: 48,
    memoryBandwidth: 768,
    estimatedPriceUSD: 4500,
    powerConsumptionWatts: 300,
    tpsScaling: 0.95,
    description: 'Previous-generation workstation powerhouse. High-reliability dual-slot card that can NVLink with a sibling for 96GB of unified space.'
  },
  {
    id: 'rtx-a5000',
    name: 'NVIDIA RTX A5000',
    category: 'gpu',
    platformType: 'NVIDIA Workstation',
    memoryType: '24GB GDDR6',
    vram: 24,
    memoryBandwidth: 768,
    estimatedPriceUSD: 2200,
    powerConsumptionWatts: 230,
    tpsScaling: 0.93,
    description: 'ECC protected 24GB enterprise runner. Offers magnificent structural cooling and rock-solid execution buffers.'
  },
  {
    id: 'rtx-a4000',
    name: 'NVIDIA RTX A4000',
    category: 'gpu',
    platformType: 'NVIDIA Workstation',
    memoryType: '16GB GDDR6',
    vram: 16,
    memoryBandwidth: 448,
    estimatedPriceUSD: 950,
    powerConsumptionWatts: 140,
    tpsScaling: 0.91,
    description: 'Ultra-thin single-slot blower. Excellent for stacking up to 4 cards inside a compact midi-tower chassis.'
  },

  // --- NVIDIA DGX & ENTERPRISE SUPERCOMPUTERS ---
  {
    id: 'dgx-gb200-nvl72',
    name: 'NVIDIA DGX GB200 NVL72 Rack',
    category: 'gpu',
    platformType: 'NVIDIA Supercomputer (Scale Rack)',
    memoryType: '30,240GB HBM3e (NVLink unified)',
    vram: 30240,
    memoryBandwidth: 129600,
    estimatedPriceUSD: 2999000,
    powerConsumptionWatts: 120000,
    tpsScaling: 0.99,
    description: 'The global absolute summit of artificial intelligence infrastructure. Fully unified liquid-cooled cabinet with 72 Blackwell GPUs connected over nvlink. Can model gargantuan dense trillion-parameter models inside pure cache at blistering velocities.'
  },
  {
    id: 'dgx-b200',
    name: 'NVIDIA DGX B200 Supernode (8-way)',
    category: 'gpu',
    platformType: 'NVIDIA Enterprise (8x GPU Node)',
    memoryType: '1,536GB HBM3e (Combined)',
    vram: 1536,
    memoryBandwidth: 64000,
    estimatedPriceUSD: 385000,
    powerConsumptionWatts: 14300,
    tpsScaling: 0.98,
    description: 'A sovereign state or enterprise-grade node holding 8x Blackwell B200 accelerators. Incredibly high context bandwidth enables massive parallel text generation sweeps.'
  },
  {
    id: 'dgx-h200',
    name: 'NVIDIA DGX H200 Node (8-way)',
    category: 'gpu',
    platformType: 'NVIDIA Enterprise (8x GPU Node)',
    memoryType: '1,128GB HBM3e (Combined)',
    vram: 1128,
    memoryBandwidth: 38400,
    estimatedPriceUSD: 299000,
    powerConsumptionWatts: 10200,
    tpsScaling: 0.97,
    description: 'The golden standard of industry training and batching complexes. Houses 8x NVIDIA H200 accelerators with revolutionary HBM3e memory throughput.'
  },
  {
    id: 'dgx-h100',
    name: 'NVIDIA DGX H100 Node (8-way)',
    category: 'gpu',
    platformType: 'NVIDIA Enterprise (8x GPU Node)',
    memoryType: '640GB HBM3 (Combined)',
    vram: 640,
    memoryBandwidth: 26800,
    estimatedPriceUSD: 249000,
    powerConsumptionWatts: 10200,
    tpsScaling: 0.96,
    description: 'The high-performance accelerator engine that booted the generative era. Features 8x legendary H100 SXM GPUs running unified across NVLink.'
  },
  {
    id: 'dgx-a100',
    name: 'NVIDIA DGX A100 Server (8-way 80G)',
    category: 'gpu',
    platformType: 'NVIDIA Enterprise (8x GPU Node)',
    memoryType: '640GB HBM2e (Combined)',
    vram: 640,
    memoryBandwidth: 16000,
    estimatedPriceUSD: 149000,
    powerConsumptionWatts: 6500,
    tpsScaling: 0.94,
    description: 'Highly effective mature enterprise server. Packs eight A100 80GB modules to run hefty enterprise models with ease.'
  },
  {
    id: 'nvidia-h100-pcie',
    name: 'NVIDIA H100 PCIe (80GB Single)',
    category: 'gpu',
    platformType: 'NVIDIA Enterprise (Single GPU)',
    memoryType: '80GB HBM3',
    vram: 80,
    memoryBandwidth: 3350,
    estimatedPriceUSD: 32000,
    powerConsumptionWatts: 350,
    tpsScaling: 0.95,
    description: 'Single enterprise PCIe monster. Designed for high density deep learning workstations and research servers.'
  },
  {
    id: 'nvidia-a100-pcie',
    name: 'NVIDIA A100 PCIe (80GB Single)',
    category: 'gpu',
    platformType: 'NVIDIA Enterprise (Single GPU)',
    memoryType: '80GB HBM2e',
    vram: 80,
    memoryBandwidth: 2039,
    estimatedPriceUSD: 12000,
    powerConsumptionWatts: 300,
    tpsScaling: 0.92,
    description: 'Professional research standard. Offers huge single-card memory bounds and ultra-high bandwidth values.'
  },
  {
    id: 'nvidia-l40s',
    name: 'NVIDIA L40S PCIe (48GB)',
    category: 'gpu',
    platformType: 'NVIDIA Enterprise PCIe',
    memoryType: '48GB GDDR6',
    vram: 48,
    memoryBandwidth: 864,
    estimatedPriceUSD: 11000,
    powerConsumptionWatts: 350,
    tpsScaling: 0.93,
    description: 'Flexible generative workstation card. Combines massive cuda-cores with high GDDR6 memory to streamline active fine-tuning.'
  },
  {
    id: 'nvidia-l4',
    name: 'NVIDIA L4 PCIe (24GB)',
    category: 'gpu',
    platformType: 'NVIDIA Enterprise PCIe',
    memoryType: '24GB GDDR6',
    vram: 24,
    memoryBandwidth: 300,
    estimatedPriceUSD: 2500,
    powerConsumptionWatts: 72,
    tpsScaling: 0.88,
    description: 'Utterly efficient single-slot accelerator. Draws barely 72W of power while supplying a generous 24GB developer framework.'
  },

  // --- NEUREALITY & CLOUD CUSTOM ACCELERATORS (N1 / N1X SERIES) ---
  {
    id: 'neureality-nr1',
    name: 'NeuReality NR1 AI Inference Card (N1 Series)',
    category: 'gpu',
    platformType: 'NeuReality NAPU Device',
    memoryType: '16GB LPDDR5 (NAPU Stream)',
    vram: 16,
    memoryBandwidth: 800,
    estimatedPriceUSD: 2200,
    powerConsumptionWatts: 150,
    tpsScaling: 0.92,
    description: 'NeuReality\'s groundbreaking NR1 Network Addressable Processing Unit (NAPU). Completely bypasses traditional CPU bottlenecks, streaming tokens directly over hardware TCP/IP lanes at incredible speeds.'
  },
  {
    id: 'neureality-nr1s',
    name: 'NeuReality NR1-S Inference Appliance (N1X Config)',
    category: 'gpu',
    platformType: 'NeuReality NAPU Server',
    memoryType: '160GB Unified NAPU Space (10-way)',
    vram: 160,
    memoryBandwidth: 8000,
    estimatedPriceUSD: 28500,
    powerConsumptionWatts: 1600,
    tpsScaling: 0.95,
    description: 'The extreme N1X multi-processor cabinet holding 10 NR1 accelerators. Achieves maximum localized query volumes using direct PCIe bypass protocols.'
  },
  {
    id: 'aws-trn1-32xl',
    name: 'AWS Trainium Trn1 Instance (16x Chips)',
    category: 'gpu',
    platformType: 'AWS Custom Cloud Node',
    memoryType: '512GB SDK HBM (Combined)',
    vram: 512,
    memoryBandwidth: 12800,
    estimatedPriceUSD: 110000,
    powerConsumptionWatts: 6000,
    tpsScaling: 0.94,
    description: 'AWS customized computing node hosting 16 Trainium chips. Massive combined footprint optimized for high efficiency.'
  },
  {
    id: 'aws-trn1x-32xl',
    name: 'AWS Trainium Trn1-x Instance (N1X Cloud Elite)',
    category: 'gpu',
    platformType: 'AWS Custom Cloud Node',
    memoryType: '512GB SDK HBM3 (Combined)',
    vram: 512,
    memoryBandwidth: 13500,
    estimatedPriceUSD: 125000,
    powerConsumptionWatts: 6500,
    tpsScaling: 0.95,
    description: 'The premier AWS custom system with next-generation Trainium1X upgrades inside a unified physical host, boosting local model pipeline throughput.'
  },

  // --- AMD RADEON DESKTOP GPUS ---
  {
    id: 'rx-7900-xtx',
    name: 'AMD Radeon RX 7900 XTX',
    category: 'gpu',
    platformType: 'AMD Desktop (RDNA3)',
    memoryType: '24GB GDDR6',
    vram: 24,
    memoryBandwidth: 960,
    estimatedPriceUSD: 929,
    powerConsumptionWatts: 355,
    tpsScaling: 0.86,
    description: 'Remarkable price-to-capacity performance. Unlocks 24GB high-speed memory for running medium models with ROCm on Linux.'
  },
  {
    id: 'rx-7900-xt',
    name: 'AMD Radeon RX 7900 XT',
    category: 'gpu',
    platformType: 'AMD Desktop (RDNA3)',
    memoryType: '20GB GDDR6',
    vram: 20,
    memoryBandwidth: 800,
    estimatedPriceUSD: 699,
    powerConsumptionWatts: 315,
    tpsScaling: 0.85,
    description: 'Extremely cost-effective 20GB discrete card. Fits 14B Q8 or 32B medium-scale quants smoothly.'
  },
  {
    id: 'rx-7900-gre',
    name: 'AMD Radeon RX 7900 GRE',
    category: 'gpu',
    platformType: 'AMD Desktop',
    memoryType: '16GB GDDR6',
    vram: 16,
    memoryBandwidth: 576,
    estimatedPriceUSD: 549,
    powerConsumptionWatts: 260,
    tpsScaling: 0.84,
    description: 'Fantastic entry into high-VRAM AMD. Exceptional bandwidth values for stable-diffusion and local text models.'
  },
  {
    id: 'rx-7800-xt',
    name: 'AMD Radeon RX 7800 XT',
    category: 'gpu',
    platformType: 'AMD Desktop',
    memoryType: '16GB GDDR6',
    vram: 16,
    memoryBandwidth: 624,
    estimatedPriceUSD: 499,
    powerConsumptionWatts: 263,
    tpsScaling: 0.84,
    description: 'Very popular 16GB choice with robust thermal metrics. Handles modern 8B parameters with ease.'
  },
  {
    id: 'rx-7700-xt',
    name: 'AMD Radeon RX 7700 XT',
    category: 'gpu',
    platformType: 'AMD Desktop',
    memoryType: '12GB GDDR6',
    vram: 12,
    memoryBandwidth: 432,
    estimatedPriceUSD: 419,
    powerConsumptionWatts: 245,
    tpsScaling: 0.82,
    description: 'Affordable 12GB layout providing clean speed for localized text assistants.'
  },
  {
    id: 'rx-7600-xt',
    name: 'AMD Radeon RX 7600 XT',
    category: 'gpu',
    platformType: 'AMD Desktop',
    memoryType: '16GB GDDR6',
    vram: 16,
    memoryBandwidth: 288,
    estimatedPriceUSD: 329,
    powerConsumptionWatts: 190,
    tpsScaling: 0.80,
    description: 'Lowest cost 16GB graphics card on the PC platform. Bus speeds are minimal, but execution volume is top-tier.'
  },
  {
    id: 'rx-6950-xt',
    name: 'AMD Radeon RX 6950 XT',
    category: 'gpu',
    platformType: 'AMD Desktop (RDNA2)',
    memoryType: '16GB GDDR6',
    vram: 16,
    memoryBandwidth: 512,
    estimatedPriceUSD: 550,
    powerConsumptionWatts: 335,
    tpsScaling: 0.81,
    description: 'Previous-generation compute titan. Solid bandwidth metrics and amazing value on secondary listings.'
  },
  {
    id: 'rx-6800-xt',
    name: 'AMD Radeon RX 6800 XT',
    category: 'gpu',
    platformType: 'AMD Desktop (RDNA2)',
    memoryType: '16GB GDDR6',
    vram: 16,
    memoryBandwidth: 512,
    estimatedPriceUSD: 420,
    powerConsumptionWatts: 300,
    tpsScaling: 0.81,
    description: 'Highly acclaimed 16GB baseline. Safe and reliable performance characteristics for long inference tasks.'
  },

  // --- AMD RYZEN LATEST STRIX HALO & OLDER APUS (AI PC) ---
  {
    id: 'apu-strix-halo-395',
    name: 'AMD Ryzen AI Max 395 (Strix Halo Flagship - 96GB)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '96GB LPDDR5X (Unified Share)',
    vram: 64,
    vramConfigurable: [32, 64, 96],
    memoryBandwidth: 546,
    estimatedPriceUSD: 1600,
    powerConsumptionWatts: 130,
    tpsScaling: 0.86,
    description: 'The premier next-generation PC APU benchmark. Insane 512-bit wide memory interface delivers a massive 546 GB/s bandwidth, completely closing the gap with dedicated computer cards while supporting up to 96GB of unified memory share.'
  },
  {
    id: 'apu-strix-halo-390',
    name: 'AMD Ryzen AI Max 390 (Strix Halo APU - 64GB)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '64GB LPDDR5X (Unified Share)',
    vram: 44,
    vramConfigurable: [16, 32, 44, 64],
    memoryBandwidth: 400,
    estimatedPriceUSD: 1200,
    powerConsumptionWatts: 110,
    tpsScaling: 0.84,
    description: 'Masterfully balanced mid-level Strix Halo offering. Unlocks massive unified RAM pools inside low cost compact business rigs.'
  },
  {
    id: 'apu-strix-halo-385',
    name: 'AMD Ryzen AI Max 385 (Strix Halo APU - 32GB)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '32GB LPDDR5X (Unified Share)',
    vram: 24,
    vramConfigurable: [16, 24, 32],
    memoryBandwidth: 300,
    estimatedPriceUSD: 950,
    powerConsumptionWatts: 90,
    tpsScaling: 0.82,
    description: 'Economic Strix Halo entry benchmark. Features robust memory-bus speeds matching premium traditional laptop setups.'
  },
  {
    id: 'apu-ryzen-ai-9-hx370',
    name: 'AMD Ryzen AI 9 HX 370 (Radeon 890M APU)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '32GB LPDDR5X Dual-Channel',
    vram: 16,
    memoryBandwidth: 135,
    estimatedPriceUSD: 1100,
    powerConsumptionWatts: 45,
    tpsScaling: 0.80,
    description: 'Flagship Zen 5 mobile/desktop APU. Features AMD Radeon 890M graphics. Relies on BIOS memory allocation to designate up to 16GB of system RAM as dedicated VRAM.'
  },
  {
    id: 'apu-ryzen-ai-9-365',
    name: 'AMD Ryzen AI 9 365 (Radeon 880M APU)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '24GB LPDDR5X Dual-Channel',
    vram: 12,
    memoryBandwidth: 120,
    estimatedPriceUSD: 850,
    powerConsumptionWatts: 35,
    tpsScaling: 0.78,
    description: 'Strix Point sub-flagship. Combines reliable NPU blocks with 12GB of shareable physical buffer room.'
  },
  {
    id: 'apu-ryzen-7-8700g',
    name: 'AMD Ryzen 7 8700G (Radeon 780M APU)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '24GB DDR5-6400 (Allocated Share)',
    vram: 16,
    memoryBandwidth: 102,
    estimatedPriceUSD: 600,
    powerConsumptionWatts: 65,
    tpsScaling: 0.78,
    description: 'The classic desktop APU champion. Outfitted with strong Radeon 780M graphics. Supports up to 16GB VRAM allocation using motherboard BIOS settings.'
  },
  {
    id: 'apu-ryzen-8840u',
    name: 'AMD Ryzen 7 8840U (Radeon 780M Hawk Point)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '32GB LPDDR5-7500 (Allocated Share)',
    vram: 16,
    memoryBandwidth: 120,
    estimatedPriceUSD: 799,
    powerConsumptionWatts: 25,
    tpsScaling: 0.79,
    description: 'Highly popular ultraportable processor. Combines Hawk Point NPU architecture with designated LPDDR5 VRAM pipelines.'
  },
  {
    id: 'apu-ryzen-7840u',
    name: 'AMD Ryzen 7 7840U / Z1 Extreme (Phoenix APU)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '16GB LPDDR5-6400 (Allocated Share)',
    vram: 8,
    memoryBandwidth: 102,
    estimatedPriceUSD: 599,
    powerConsumptionWatts: 15,
    tpsScaling: 0.77,
    description: 'The engine that runs the modern handheld gaming console storm. Outstanding portable AI accelerator with shared memory maps.'
  },
  {
    id: 'apu-ryzen-6800u',
    name: 'AMD Ryzen 7 6800U (Radeon 680M APU - Older)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '16GB LPDDR5 (Allocated Share)',
    vram: 8,
    memoryBandwidth: 100,
    estimatedPriceUSD: 450,
    powerConsumptionWatts: 15,
    tpsScaling: 0.74,
    description: 'Older but highly-active portable processing chip. Unlocks 8GB allocated local vram slots.'
  },
  {
    id: 'apu-ryzen-5700g',
    name: 'AMD Ryzen 7 5700G (Radeon Vega 8 - Classic Old)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '16GB DDR4-3200 (System Share)',
    vram: 8,
    memoryBandwidth: 44,
    estimatedPriceUSD: 299,
    powerConsumptionWatts: 65,
    tpsScaling: 0.68,
    description: 'A historic modular desktop masterpiece. Though bound to older Vega graphics architecture and tight DDR4 memory lines, it remains active in many customized home systems.'
  },
  {
    id: 'apu-ryzen-4700u',
    name: 'AMD Ryzen 7 4700U (Radeon Vega 7 APU)',
    category: 'gpu',
    platformType: 'AMD APU / AI PC',
    memoryType: '16GB DDR4 (Allocated Share)',
    vram: 6,
    memoryBandwidth: 35,
    estimatedPriceUSD: 250,
    powerConsumptionWatts: 15,
    tpsScaling: 0.65,
    description: 'Decentralized early APU engine. Provides high baseline utility for simple localized NLP queries.'
  },
  {
    id: 'apu-intel-ultra-7-258v',
    name: 'Intel Core Ultra 7 258V (Lunar Lake NPU)',
    category: 'gpu',
    platformType: 'Intel APU / AI PC',
    memoryType: '32GB LPDDR5X On-Package',
    vram: 16,
    memoryBandwidth: 136,
    estimatedPriceUSD: 1050,
    powerConsumptionWatts: 30,
    tpsScaling: 0.79,
    description: 'Copilot+ PC solution with on-board memory. Blazing system efficiency paired with high-performance integrated Xe2 graphics.'
  },

  // --- APPLE SILICON UNIFIED DESKTOP & LAPTOP (M1 TO M5 GENERATIONS) ---
  
  // ==================== M5 GENERATION (NEXT-GEN) ====================
  {
    id: 'apple-m5-ultra',
    name: 'Apple M5 Ultra (Next-Gen Concept)',
    category: 'mac',
    platformType: 'Unified Mac Desktop (Next-Gen)',
    memoryType: '256GB Unified Memory',
    vram: 204,
    vramConfigurable: [64, 128, 192, 256],
    memoryBandwidth: 1400,
    estimatedPriceUSD: 6999,
    powerConsumptionWatts: 150,
    tpsScaling: 0.96,
    description: 'The upcoming ultimate zenith of Apple Silicon design. A massive 2048-bit memory bus pushes bandwidth up to 1400 GB/s, rendering standard reasoning parameters fluidly inside massive pools.'
  },
  {
    id: 'apple-m5-max',
    name: 'Apple M5 Max',
    category: 'mac',
    platformType: 'Unified Mac Laptop / Desktop',
    memoryType: '144GB Unified Memory',
    vram: 115,
    vramConfigurable: [48, 96, 144],
    memoryBandwidth: 800,
    estimatedPriceUSD: 4599,
    powerConsumptionWatts: 50,
    tpsScaling: 0.94,
    description: 'Next-generation laptop masterclass. Outstretched raw system memory lanes enable portable developer runs on large local neural weights.'
  },
  {
    id: 'apple-m5-pro',
    name: 'Apple M5 Pro',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '72GB Unified Memory',
    vram: 57,
    vramConfigurable: [24, 48, 72],
    memoryBandwidth: 384,
    estimatedPriceUSD: 2799,
    powerConsumptionWatts: 35,
    tpsScaling: 0.92,
    description: 'Next-generation Pro-oriented mobile chip setup. Substantially raised bandwidth metrics make local developer loops smooth.'
  },
  {
    id: 'apple-m5-base',
    name: 'Apple M5 (Base)',
    category: 'mac',
    platformType: 'Unified Mac Base Line',
    memoryType: '32GB Unified Memory',
    vram: 25,
    vramConfigurable: [16, 24, 32],
    memoryBandwidth: 170,
    estimatedPriceUSD: 1299,
    powerConsumptionWatts: 20,
    tpsScaling: 0.90,
    description: 'Efficient entry computing system designed around next-generation neural engines.'
  },

  // ==================== M4 GENERATION ====================
  {
    id: 'mac-studio-m4-ultra',
    name: 'Mac Studio (M4 Ultra - Upcoming Flagship)',
    category: 'mac',
    platformType: 'Unified Mac Desktop',
    memoryType: '192GB Unified Memory',
    vram: 153,
    vramConfigurable: [64, 128, 192, 256],
    memoryBandwidth: 1000,
    estimatedPriceUSD: 5999,
    powerConsumptionWatts: 140,
    tpsScaling: 0.94,
    description: 'The premier modern Mac-based hosting server. Estimated 1000 GB/s unified bandwidth delivers blistering speeds, making the largest 70B and 405B models stream like lightweight assistants.'
  },
  {
    id: 'apple-m4-max',
    name: 'MacBook Pro (M4 Max - 128GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '128GB Unified Memory',
    vram: 102,
    vramConfigurable: [36, 48, 64, 128, 192],
    memoryBandwidth: 546,
    estimatedPriceUSD: 4299,
    powerConsumptionWatts: 45,
    tpsScaling: 0.92,
    description: 'Superb mobile supercomputer. Upgraded 546 GB/s memory bandwidth outputs responsive streaming for enormous models on-the-go.'
  },
  {
    id: 'apple-m4-pro',
    name: 'MacBook Pro (M4 Pro - 64GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '64GB Unified Memory',
    vram: 51,
    vramConfigurable: [24, 48, 64],
    memoryBandwidth: 273,
    estimatedPriceUSD: 2599,
    powerConsumptionWatts: 35,
    tpsScaling: 0.90,
    description: 'Upgraded modern pro laptop featuring superb M4 bandwidth. Ideal setup for light developer tooling.'
  },
  {
    id: 'apple-m4-base',
    name: 'Mac Mini / MacBook Pro (M4 - 32GB)',
    category: 'mac',
    platformType: 'Unified Mac Desktop/Laptop',
    memoryType: '32GB Unified Memory',
    vram: 25,
    vramConfigurable: [16, 24, 32],
    memoryBandwidth: 150,
    estimatedPriceUSD: 999,
    powerConsumptionWatts: 25,
    tpsScaling: 0.89,
    description: 'Extremely cost-effective entry point into the M4 system. Beautifully fast execution speeds for lightweight LLMs.'
  },

  // ==================== M3 GENERATION ====================
  {
    id: 'apple-m3-ultra',
    name: 'Mac Studio (M3 Ultra)',
    category: 'mac',
    platformType: 'Unified Mac Desktop',
    memoryType: '192GB Unified Memory',
    vram: 153,
    vramConfigurable: [64, 128, 192],
    memoryBandwidth: 800,
    estimatedPriceUSD: 5499,
    powerConsumptionWatts: 120,
    tpsScaling: 0.90,
    description: 'High-bandwidth corporate centerpiece. Perfect setup for continuous localized reasoning hosting pools.'
  },
  {
    id: 'apple-m3-max',
    name: 'MacBook Pro (M3 Max - 128GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '128GB Unified Memory',
    vram: 102,
    vramConfigurable: [36, 48, 64, 96, 128],
    memoryBandwidth: 400,
    estimatedPriceUSD: 3999,
    powerConsumptionWatts: 45,
    tpsScaling: 0.88,
    description: 'Outstanding developer workstation. Direct GPU-on-die access to massive system assets prevents transfer latency.'
  },
  {
    id: 'apple-m3-pro',
    name: 'MacBook Pro (M3 Pro - 36GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '36GB Unified Memory',
    vram: 28,
    vramConfigurable: [18, 36],
    memoryBandwidth: 150,
    estimatedPriceUSD: 2399,
    powerConsumptionWatts: 35,
    tpsScaling: 0.88,
    description: 'Elegant developer assistant. Silently runs 14B parameter models in near-lossless format.'
  },
  {
    id: 'apple-m3-base',
    name: 'MacBook Air / Pro (M3 - 24GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '24GB Unified Memory',
    vram: 19,
    vramConfigurable: [8, 16, 24],
    memoryBandwidth: 100,
    estimatedPriceUSD: 1499,
    powerConsumptionWatts: 15,
    tpsScaling: 0.84,
    description: 'Fanless and fully silent travel assistant. Fits modern 8B parameter models in 4-bit quants easily.'
  },

  // ==================== M2 GENERATION ====================
  {
    id: 'apple-m2-ultra',
    name: 'Mac Studio (M2 Ultra - 192GB)',
    category: 'mac',
    platformType: 'Unified Mac Desktop',
    memoryType: '192GB Unified Memory',
    vram: 153,
    vramConfigurable: [64, 128, 192],
    memoryBandwidth: 800,
    estimatedPriceUSD: 5299,
    powerConsumptionWatts: 120,
    tpsScaling: 0.89,
    description: 'Extremely potent dual-engine unified processor. Silently supports incredibly large 70B reasoners inside active memory buffers.'
  },
  {
    id: 'apple-m2-max',
    name: 'MacBook Pro (M2 Max - 96GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '96GB Unified Memory',
    vram: 76,
    vramConfigurable: [32, 64, 96],
    memoryBandwidth: 400,
    estimatedPriceUSD: 3499,
    powerConsumptionWatts: 40,
    tpsScaling: 0.87,
    description: 'Highly successful previous-generation mobile benchmark. Seamlessly splits 34B MoEs like Mixtral.'
  },
  {
    id: 'apple-m2-pro',
    name: 'MacBook Pro (M2 Pro - 32GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '32GB Unified Memory',
    vram: 25,
    vramConfigurable: [16, 32],
    memoryBandwidth: 200,
    estimatedPriceUSD: 1999,
    powerConsumptionWatts: 30,
    tpsScaling: 0.86,
    description: 'Reliable mobile workstation featuring solid 200 GB/s bandwidth for intermediate workloads.'
  },
  {
    id: 'apple-m2-base',
    name: 'MacBook Air / Mini (M2 - 24GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '24GB Unified Memory',
    vram: 19,
    vramConfigurable: [8, 16, 24],
    memoryBandwidth: 100,
    estimatedPriceUSD: 1299,
    powerConsumptionWatts: 15,
    tpsScaling: 0.83,
    description: 'Ultraportable local engine. Outstanding for reading brief PDFs and testing light local prompts.'
  },

  // ==================== M1 GENERATION ====================
  {
    id: 'mac-studio-m1-ultra',
    name: 'Mac Studio (M1 Ultra - Legacy Premium)',
    category: 'mac',
    platformType: 'Unified Mac Desktop',
    memoryType: '128GB Unified Memory',
    vram: 102,
    vramConfigurable: [64, 128],
    memoryBandwidth: 800,
    estimatedPriceUSD: 3199,
    powerConsumptionWatts: 110,
    tpsScaling: 0.89,
    description: 'Exceptional value in the used market. Retains the enormous 800 GB/s bandwidth bus, outperforming many newer Max series on raw speed.'
  },
  {
    id: 'apple-m1-max',
    name: 'MacBook Pro (M1 Max - 64GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '64GB Unified Memory',
    vram: 51,
    vramConfigurable: [32, 64],
    memoryBandwidth: 400,
    estimatedPriceUSD: 1899,
    powerConsumptionWatts: 35,
    tpsScaling: 0.86,
    description: 'Highly affordable refurbished powerhouse. Low structural power pull with top-tier 400 GB/s bus rates.'
  },
  {
    id: 'apple-m1-pro',
    name: 'MacBook Pro (M1 Pro - 32GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '32GB Unified Memory',
    vram: 25,
    vramConfigurable: [16, 32],
    memoryBandwidth: 200,
    estimatedPriceUSD: 1499,
    powerConsumptionWatts: 30,
    tpsScaling: 0.85,
    description: 'Great refurbished entry card. High speed memory bus makes small local models feel incredibly responsive.'
  },
  {
    id: 'apple-m1-base',
    name: 'MacBook Air (M1 - 16GB)',
    category: 'mac',
    platformType: 'Unified Mac Laptop',
    memoryType: '16GB Unified Memory',
    vram: 12,
    vramConfigurable: [8, 16],
    memoryBandwidth: 68,
    estimatedPriceUSD: 799,
    powerConsumptionWatts: 10,
    tpsScaling: 0.81,
    description: 'The cheapest local unified entry point. Best used to design lightweight web interfaces or sandbox small 3B models.'
  },

  // --- PC CPU CONFIGS (CPU-ONLY INFERENCE) ---
  {
    id: 'pc-cpu-ddr5-dual',
    name: 'Typical PC (DDR5 Dual-Channel RAM)',
    category: 'pc_cpu',
    platformType: 'Intel/AMD System (CPU Only)',
    memoryType: '64GB DDR5-6000',
    vram: 64,
    vramConfigurable: [16, 32, 64, 128],
    memoryBandwidth: 96,
    estimatedPriceUSD: 1200,
    powerConsumptionWatts: 150,
    tpsScaling: 0.65,
    description: 'Standard CPU offload execution. Can support enormous parameter files, but speed suffers from severe RAM bandwidth bottlenecks.'
  },
  {
    id: 'pc-cpu-ddr4-dual',
    name: 'Typical PC (DDR4 Dual-Channel RAM)',
    category: 'pc_cpu',
    platformType: 'Intel/AMD System (CPU Only)',
    memoryType: '32GB DDR4-3200',
    vram: 32,
    vramConfigurable: [16, 32, 64],
    memoryBandwidth: 50,
    estimatedPriceUSD: 700,
    powerConsumptionWatts: 125,
    tpsScaling: 0.60,
    description: 'Previous-generation PC framework. Fully capable of loading custom datasets, though speeds are bound by system bus limits.'
  },
  {
    id: 'workstation-cpu-octa',
    name: 'Threadripper Workstation (DDR5 Octa-Channel)',
    category: 'pc_cpu',
    platformType: 'AMD Threadripper Pro',
    memoryType: '256GB DDR5 Quad/Octa-Channel',
    vram: 256,
    vramConfigurable: [128, 256, 512],
    memoryBandwidth: 384,
    estimatedPriceUSD: 6000,
    powerConsumptionWatts: 350,
    tpsScaling: 0.75,
    description: 'Multi-channel workstation engine. Fits the largest open reasoning networks without requiring complex multi-card layouts.'
  }
];
